### PR TITLE
Specify array length in a 'data-xxx' attribute

### PR DESCRIPTION
**Pull request by stanio**
Related to #128 and #131, this is just to give an idea how it could be made not to interfere with content <kbd>Copy</kbd>+<kbd>Paste</kbd>.

This is not complete solution as styling needs to be tweaked further.

### CODE REVIEW

**Comment by stanio** [comment]
Some shots:

array-counter-1

array-counter-2

array-counter-3

_Counter color is different for the sake of experiment._

**Comment by bhollis** [comment]
Nice! How does the copy/paste look?

I struggled with the styling on this last time I tried it too... they always looked too bold. Any ideas?

**Comment by stanio** [comment]
> Nice! How does the copy/paste look?

It's unchanged, as far as I've observed.

> I struggled with the styling on this last time I tried it too... they always looked too bold. Any ideas?

I don't really have idea for better styling.

**Comment by bhollis** [comment]
Nice, I checked out the branch and this works great! Good job thinking up this approach, it's really nice. Let me try out my previous branch with this technique.

**Comment by Bob7074** [comment]
Nice

**Comment by stanio** [comment]
FWIW, I'm revisiting my approach from https://github.com/bhollis/jsonview/issues/128#issuecomment-241284385, and here's a demo version I'm currently using:

https://github.com/user-attachments/assets/481e90c0-2d13-4fe8-bad7-e9ff6bd018bf

I've abandoned the length/size display but show element indices when arrays are expanded.  This is accomplished by simple style (stanio/jsonview@e33d49d) even with the current JSONView version – no extra meta-data or script changes necessary.

The main feature for me is displaying the collapsed content as much as visible inline (on one line).  This allows me to see complete nested objects while collapsed, given they have few properties and short values.

**Pull request closed without merging**
